title: Using Spring JdbcTemplate with JdbcTemplateMapper
google_site_verification: QjeiEv1L9u47joCGHUfh_p5LJ0kIqvimFLS4kxSVLFw
remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme